apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:jsw1993/gitopsv2.git
      targetRevision: main
      ref: values
    - repoURL: https://charts.jetstack.io
      chart: 
      targetRevision: v1.17.1
      helm:
        releaseName: cert-manager
        valueFiles:
        - homelab/values/cert-manager.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true