apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL:
      targetRevision: main
      ref: values
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.17.2  # specify the chart version
      helm:
        valueFiles:
        - $values/homelab/values/cert-manager.yaml
        ignoreMissingValueFiles: false
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 15.7.1
    helm:
      valueFiles:
      - $values/homelab/values/cert-manager.yaml
  - repoURL: 'https://github.com/jsw1993/gitopsv2.git'
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true