apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-issuer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jsw1993/gitopsv2.git  # Replace with your repo URL
    targetRevision: HEAD
    path: homelab/cert-manager  # Path in your repo where the cilium-lb-ip-pool.yaml resides
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager  # Modify based on where you want to deploy
  ignoreDifferences:
  - group: ""
    kind: Secret
    syncPolicy:
      automated:
        prune: true
        selfHeal: true