apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: truenas-csi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jsw1993/gitopsv2.git  # Replace with your repo URL
    targetRevision: HEAD
    path: homelab/truenas-csi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system  # Modify based on where you want to deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true