apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: argocd
spec:
  endpointSelector: {}
  ingress:
    - fromCIDRSet:
        - cidr: 172.16.50.0/24
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: argocd
    - fromEndpoints:
        - matchExpressions:
            - key: reserved:ingress
              operator: Exists
  egress:
    - toEndpoints:
        - {}
    - toFQDNs:
        - matchPattern: "*.github.io"
    - toFQDNs:
        - matchName: charts.jetstack.io
    - toFQDNs:
        - matchName: github.com
    - toEntities:
        - kube-apiserver