apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: save-it-aws
spec:
  acme:
    email: james@save-it.co.uk
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z00114353FRO5DCSYJTJ7
          region: eu-west-2
          accessKeyIDSecretRef:
            name: route53
            key: key
          secretAccessKeySecretRef:
            name: route53
            key: secret