apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: save-it-aws
spec:
  acme:
    email: devops@intelligent-data-collection.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: route53

    solvers:
    - dns01:
        route53:
          hostedZoneID: Z2S4V27PZ8LJEF
          region: eu-west-2